### ISSUE TITLE
EEP Solarized Palettes

### ISSUE THREAD

**Issue by soonerroadie** [boolbag/EditPad-Goodies#1]
I saw on your page about the MishMash color palette that one of the images you posted had a Solarized color palette. Did you creates those and would you be willing to share?

By the way, followed your instructions on MishMash and it worked great. Thanks for that! Glad to see other EPP users out there (a lot of the content I see these days is many years old).

**Comment by boolbag** [comment]
As far as I recall, all the images are MishMash.
By the way will soon post an update for EPP8.

**Comment by soonerroadie** [comment]
Just to clarify - I noticed in one of the screen shots that your list of palettes there was a Solarized palette available (not that it was actually being used). Nevertheless, Soliarized is available on EPP8 (as is, now, MishMash). Thanks for updating.

**Comment by boolbag** [comment]
Hey there,
Just to clarify, I have no idea what screenshot you are referring to.
Warm wishes,
-bb

**Comment by soonerroadie** [comment]
https://github.com/boolbag/EditPad-Goodies/raw/master/Making%20Text%20Pretty%20-%20Syntax%20Coloring%20and%20Color%20Palettes/Color%20Palettes/MishMash/img/color-palette-name.jpg

The first two entries are Solarized Light and Dark.

**Comment by boolbag** [comment]
Ah, now I understand.
Yes, this is from a list of color palettes within EPP itself, as I'm sure you've gathered by now.
Thank you for your feedback. :)
